baseURL = "https://low-level-luke.me/"
languageCode = "en-gb"
title = "low-level-luke"
theme = "PaperMod"
[pagination]
pagerSize = 10

[params]
defaultTheme = "dark"
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

  [params.homeInfoParams]
  Title = "low-level-luke"
  Content = "Systems programming, performance, and things I'm learning."

[[params.socialIcons]]
name = "email"
url = "mailto:luke61996@gmail.com"

[[params.socialIcons]]
name = "x"
url = "https://x.com/MrDust0"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/323409278733910017"

[params.profileMode]
enabled = false

[markup]
  [markup.highlight]
  style = "monokai"
  lineNos = false
  codeFences = true
  guessSyntax = true
  noClasses = false

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archives/"
weight = 30
